name: LSA APP - iOS IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.1
  PYTHON_VERSION: 3.12.8
  FLET_CLI_VERSION: 0.27.6
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1
  UV_NO_PROGRESS: 1

jobs:
  build:
    runs-on: macos-latest  # Must be macOS for iOS builds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install flet-cli ${{ env.FLET_CLI_VERSION }}
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==$FLET_CLI_VERSION

      - name: Install Xcode command line tools
        run: |
          xcode-select --install || true

      - name: Flet Build IPA
        run: |
          flet build ipa --verbose \
            --build-number=$BUILD_NUMBER \
            --build-version=$BUILD_VERSION
        # Note: You may need additional flags for signing, e.g.:
        # --codesign-identity="Apple Development: Your Name (TEAMID)"
        # --provisioning-profile="path/to/profile.mobileprovision"

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: ipa-build-artifact
          path: build/ipa
          if-no-files-found: error
          overwrite: false
